config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             controllers: {
                omniauth_callbacks: 'users/omniauth_callbacks'
              }

  devise_scope :user do
    delete 'sign_out',
        to: 'devise/sessions#destroy',
        as: :destroy_user_session
  end

  scope '(:locale)', locale: /pl|en/ do
    root 'home#index'

    resources :districts, only: [:show]
    resources :discussions, only: [:index, :show, :create, :destroy]
    resources :comments, only: [:create]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :create, Discussion, author_id: user.id

      can :destroy, Discussion do |discussion|
        discussion.author_id == user.id &&
          discussion.comments.by(user) == discussion.comments
      end

      can :create, Comment, author_id: user.id
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :author,
             class_name: 'User',
             foreign_key: 'author_id',
             required: true

  belongs_to :discussion,
             required: true

  # Thread is our name for a set of comments replying to another comment
  belongs_to :thread, class_name: 'Comment'

  has_many :replies,
           class_name: 'Comment',
           foreign_key: 'thread_id'

  default_scope { order(:created_at) }

  scope :by, ->(user) { where(author: user) }


  # def purge
  #   content = I18n.t 'discussions.comment.content.purged'
  #   save
  # end

end

app/models/concerns/nondeletable.rb
# Provides a Concern for any Model class entities of which should NEVER be destroyed.
# In model class use it with
#   include Nondeletable
# somewhere inside the model class definition. This guards against "destroy", probably
# not effective against "delete".

module Nondeletable extend ActiveSupport::Concern

  included do
    before_destroy :prevent_destroy
  end

  private

  def prevent_destroy
    logger.error "PREVENTING DESTROY of #{self.class.name}!!!"
    errors.add :base,
      I18n.t('errors.messages.nondeletable', class_name: self.class.name)
    false
  end

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :author,
             class_name: 'User',
             foreign_key: 'author_id',
             required: true

  has_many :comments, dependent: :destroy

  validates_presence_of :fid

  before_destroy :check_comments, prepend: true


  scope :newest_first, -> { order(created_at: :desc) }

  scope :about, ->(fid) { where(fid: fid).newest_first }

  scope :recently_created, -> { newest_first.limit(5) }

  scope :recently_commented, -> {
    select('discussions.*', 'MAX(comments.created_at)').
    joins(:comments).
    group('discussions.id').
    order('MAX(comments.created_at) DESC').
    limit(5)

    # # The original SQL version
    # find_by_sql(
    #   'SELECT discussions.*, MAX(comments.created_at) AS sort
    #    FROM discussions
    #    INNER JOIN comments ON comments.discussion_id = discussions.id
    #    GROUP BY discussions.id
    #    ORDER BY SORT DESC
    #    LIMIT 5')
  }

  # Please note it does NOT include the discussion author unless that user
  # is also an author of at least a single comment in this discussion
  def commenters
    # User.joins(:comments).where(comments: {discussion_id: id}).uniq
    User.where(id: comments.pluck(:author_id))
  end


  private

  def check_comments
    commenters.count < 2
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  include Nondeletable

  devise :rememberable,
         :trackable,
         :omniauthable,
         omniauth_providers: [:facebook, :google_oauth2]

  has_many :discussions,
           foreign_key: 'author_id'

  has_many :comments,
           foreign_key: 'author_id'

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale


  def render_error(msg, options={})
    error_json = {
      message: msg,
      type: options[:type] || :general
    }
    error_json[:details] = options[:details] if options[:details]

    render(
      json: error_json,
      status: options[:status] || :bad_request
    )
  end

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale] = I18n.locale
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include Ajaxable

  load_and_authorize_resource only: [:create]
  layout false

  def create
    @comment.save!
    @discussion = @comment.discussion
    render 'discussions/show'
  end


  private

  def comment_params
    params.require(:comment).
           permit(:content, :discussion_id).
           merge(author: current_user)
  end
end

app/controllers/concerns/ajaxable.rb
module Ajaxable
  extend ActiveSupport::Concern

  included do
    rescue_from CanCan::AccessDenied do |exception|
      render_error(exception.message, status: current_user ? 403 : 401)
    end
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  include Ajaxable

  load_and_authorize_resource only: [:create, :destroy]
  layout false, except: :show

  def index
    if params[:fid]
      @discussions = Discussion.about params[:fid]
      if params[:list_only]
        render partial: 'list', object: @discussions
      end
    else
      @recently_created = Discussion.recently_created
      @recently_commented = Discussion.recently_commented.all
      render 'recent'
    end
  end

  def show
    @discussion = Discussion.find params[:id]

    if request.xhr?
      render 'show', layout: false
    else
      # render 'index', layout: true
      render 'home/index', layout: true
    end
  end

  def create
    @discussion.save!

    @discussions = Discussion.about params[:discussion][:fid]
    render partial: 'list', object: @discussions
  end

  def destroy
    @discussion.destroy!

    head :ok
  end

  private

  def discussion_params
    params.require(:discussion).
      permit(:title, :fid).
      merge(author: current_user)
  end
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController

  # GET /district/:id
  # Here id == FID of the district WMS feature (should be unique)
  # WARNING: this will NOT be true for cross-WMS app
  #         (same FIDs for different features in two distinct cities)
  # We may use this operation to load feature-related data from our DB
  def show
    @data = params[:wms_data]
    render partial: 'show', layout: false
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def self.provides_callback_for(provider)
      class_eval %Q{
        def #{provider}
          @user = User.from_omniauth(env["omniauth.auth"])

          if @user.persisted?
            sign_in_and_redirect @user, event: :authentication
            set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
          else
            session["devise.#{provider}_data"] = env["omniauth.auth"]
            redirect_to root_url
          end
        end
      }
    end

    [:facebook, :google_oauth2].each do |provider|
      provides_callback_for provider
    end

    def after_omniauth_failure_path_for(scope)
      root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def body_data_dispatch
    [controller.controller_name, controller.action_name].compact.join(':')
  end

  def en?
    I18n.locale == :en
  end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper

  # Show 'time since' in a user friendly way
  def time_ago(time)
    if Time.now < time || Time.now - time > 1.day
      l(time.in_time_zone('CET'), format: :short)
    else
      time_ago_in_words(time) + ' ' + t('datetime.ago')
    end
  end

  def discussion_title(discussion)
    if discussion.title.present?
      discussion.title
    else
      t 'discussions.discussion.title.default',
        id: discussion.id, fid: discussion.fid
    end
  end

end

app/helpers/districts_helper.rb
module DistrictsHelper

  # Turns number of milliseconds since epoch to Time and prints it
  def mseconds_since_epoch_to_time(mseconds)
    Time.at(mseconds.to_i / 1000).strftime('%d.%m.%Y')
  end

end

app/views/discussions/_form.html.haml
= form_for Discussion.new, remote: true do |f|

  = f.hidden_field :fid, value: params[:fid]

  .form-group
    = f.label :title
    = f.text_field :title,
      placeholder: t('discussions.discussion.title.new_default'),
      class: 'form-control'

  = f.submit t('discussions.discussion.save'), class: 'btn btn-default btn-xs'

app/views/discussions/_list.html.haml
- if list.present?

  .panel-group.discussion-list{ role: 'tablist' }
    - list.each do |discussion|
      .panel.panel-default
        .panel-heading{ role: 'tab' }
          %a.collapsed{ href: "[data-discussion=#{discussion.id}]",
          data: { toggle: 'collapse', parent: '.discussion-list' }}
            = discussion_title discussion
          .pull-right
            - if can?(:destroy, discussion)
              = link_to discussion_path(id: discussion.id),
                        method: :delete, remote: true, class: 'delete',
                        data: { confirm: t('discussions.delete_confirmation') } do
                = icon('times')
        .panel-collapse.collapse.discussion-body{ role: 'tabpanel',
        data: { discussion: discussion.id }}
          .panel-body

- else
  .alert.alert-info
    - nothing ||= t('discussions.no_discussions')
    = nothing

app/views/discussions/index.html.haml
%h4.text-center
  = t 'discussions.title'

%dl.dl-horizontal
  %dt= t 'discussions.district'
  %dd= params[:district]
  - if params[:zone].present?
    %dt= t 'discussions.zone'
    %dd= params[:zone]
  %dt= t 'krakow.mpzp.FID'
  %dd
    = params[:fid]
    %i.fa.fa-question{ title: t('help.fid') }


- if can?(:create, Discussion)

  .btn.btn-success.btn-xs{ data: { toggle: 'collapse', placement: 'bottom' },
  href: '#new-discussion',
  title: t('discussions.discussion.new.title') }
    %i.fa.fa-plus
    = t 'discussions.discussion.new.label'

  .collapse#new-discussion
    .row
      .col-lg-9
        = render 'form'

- else

  .btn-group
    .btn.btn-success.btn-xs.disabled
      %i.fa.fa-plus
      = t 'discussions.discussion.new.label'
    .btn.btn-success.btn-xs{ data: { placement: 'bottom' },
    title: t('discussions.discussion.new.please_login_title') }
      %i.fa.fa-question


#discussions
  = render partial: 'list', object: @discussions

app/views/discussions/recent.html.haml
- if Discussion.count == 0

  %h4.text-center
    = t 'activerecord.models.discussions'

  .alert.alert-info
    = t '.no_discussions'

- else

  %h4.text-center
    = t '.recently_created_title'

  = render partial: 'list',
           object: @recently_created,
           locals: { nothing: t('.no_discussions') }

  - if @recently_commented.present?

    %h4.text-center
      = t '.recently_commented_title'

    = render partial: 'list',
             object: @recently_commented

app/views/discussions/show.html.haml
%ul.list-group.discussion

  %li.list-group-item.discussion-header
    %h3
      = link_to discussions_path(fid: @discussion.fid, list_only: true),
                id: 'back-to-discussions',
                remote: true, class: 'pull-left' do
        = icon('arrow-left')
    %h4.list-group-item-heading
      = discussion_title @discussion

  - @discussion.comments.each do |comment|
    %li.list-group-item.discussion-item
      .avatar
        %img{ src: comment.author.image }
      .comment-body
        %small.time
          = comment.author.name
          = time_ago comment.created_at
        %p
          = comment.content

.box
  .avatar
    %img{ src: current_user.image }
  .page-feed-content
    = form_for Comment.new, remote: true do |f|
      .form-group
        = f.hidden_field :discussion_id, value: @discussion.id
        = f.text_area :content,
          placeholder: t('discussions.comment.content.new_default'),
          class: 'form-control'

      = f.submit t('discussions.comment.save'), class: 'btn btn-default btn-xs'

app/views/districts/_show.html.haml
%h4.text-center
  = @data[:NAZWA]
  - if @data[:NR_PLANU].to_i != 0
    = surround '(',')' do
      = t 'krakow.mpzp.NR_PLANU'
      = @data[:NR_PLANU]


%dl.dl-horizontal
  %dt= t 'krakow.mpzp.Status'
  %dd= t "krakow.mpzp.#{@data[:STATUS]}"


%dl.dl-horizontal
  %dt= t 'map.dates'
  %dd

  %small
    - %w(DATA_PRZYS DATA_UCHWA DATA_DUWM DATA_OBOWI).each do |key|
      %dt= t "krakow.mpzp.#{key}"
      %dd
        - if @data[key].present?
          = mseconds_since_epoch_to_time @data[key]
        - else
          %em.text-muted
            = surround '(',')' do
              = t 'map.no_date'

%dl.dl-horizontal
  %dt= t 'map.additional_data'
  %dd

  %small
    - %w(PROWADZACY WYKONANIE FID).each do |key|
      %dt= t "krakow.mpzp.#{key}"
      %dd
        - if @data[key].present?
          = @data[key]
          - if key == 'FID'
            %i.fa.fa-question{ title: t('help.fid') }
        - else
          %em.text-muted
            = surround '(',')' do
              = t 'map.no_data'


%dl.dl-horizontal
  %dt= t 'krakow.mpzp.BIP'
  %dd
    %a{ href: @data[:WWW] }
      = t 'krakow.mpzp.bip_link'

app/views/home/_instructions.html.haml
%h4.text-center
  = t 'instructions.welcome', title: t('title')

%p
  = t 'instructions.what_you_see', city: 'Kraków'

%p
  = t 'instructions.what_you_see_2'

%dl.dl-horizontal
  %dt= t 'instructions.basics.title'
  %dd

  %small
    %dt= t 'instructions.basics.click_district.label'
    %dd= t 'instructions.basics.click_district.effect'

    %dt= t 'instructions.basics.click_zone.label'
    %dd= t 'instructions.basics.click_zone.effect'

    %dt
      = icon 'expand'
      = t 'instructions.basics.zoom_out.label'
    %dd= t 'instructions.basics.zoom_out.effect'

    %dt
      = icon('facebook-square', '', class: 'facebook')
      = icon('google-plus-square', '', class: 'google')
      = t 'instructions.basics.fb_g_plus.label'
    %dd= t 'instructions.basics.fb_g_plus.effect'


    %dt TODO Add further
    %dd instructions here...

%p= t 'instructions.wishes'

app/views/home/index.html.haml
=content_for :action_nav do
  %ul.nav.navbar-nav.panel-menu
    %li
      = link_to '#', id: 'zoom-out-button',
      data: { placement: 'bottom' },
      title: t('nav.zoom_out') do
        = icon 'expand'

app/views/layouts/_flash.html.haml
.flash-container
  - if alert
    .flash-alert
      = alert
  - elsif notice
    .flash-notice
      = notice

app/views/layouts/_head.html.haml
%head
  %meta{charset: "utf-8"}
  %meta{viewport: "width=device-width, initial-scale=1.0"}
  %title= t 'title'

  %link(href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css')

  =# favicon_link_tag 'favicon.ico'
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags

app/views/layouts/_left_section.html.haml
#left-section
  %ul.tab-pane
    - tab_data = { toggle: 'tab', placement: 'right' }
    %li.active
      %a{ href: '#info-tab',
          data: tab_data,
          title: t('nav.tabs.info') }
        = icon('map-marker')
    %li
      %a{ href: '#discussions-tab',
          data: tab_data,
          title: t('nav.tabs.discussions') }
        = icon('weixin')
    %li
      %a{ href: '#amendments-tab',
          data: tab_data,
          title: t('nav.tabs.amendments') }
        = icon('files-o')
    %li
      %a{ href: '#profile-tab',
          data: tab_data,
          title: t('nav.tabs.profile') }
        = icon('user')

  .tab-content
    #info-tab.tab-pane.active
      = render 'home/instructions'
    #discussions-tab.tab-pane
      #discussions
        = t 'nav.tabs.discussions'
    #amendments-tab.tab-pane
      = t 'nav.tabs.amendments'
    #profile-tab.tab-pane
      = t 'nav.tabs.profile'

app/views/layouts/_navbar.html.haml
%header.navbar.navbar-fixed-top.navbar-default(role="navigation")
  .container-fluid
    .row
      .col-xs-12.col-sm-5.top-left-panel
        %a.logo(href=root_path)
          = icon('cubes')
          = t('title')
        .btn-group.btn-group-xs.pull-right.navbar-btn
          = link_to 'EN', { locale: :en },
                    title: t('nav.to_en'),
                    data: { placement: 'bottom' },
                    class: "btn btn-default #{'active' if en?}"
          = link_to 'PL', { locale: :pl },
                    title: t('nav.to_pl'),
                    data: { placement: 'bottom' },
                    class: "btn btn-default #{'active' unless en?}"

      .col-xs-12.col-sm-7.top-panel
        =yield :action_nav
        %ul.nav.navbar-nav.pull-right.panel-menu
          - if current_user
            %li.dropdown
              %a.dropdown-toggle.account(href="#" data-toggle="dropdown")
                .avatar
                  %img.img-rounded{src: current_user.image}
                = icon('angle-down', '', class: 'pull-right')
                .user-mini.pull-right
                  %span.welcome= t('welcome')
                  %span= current_user.name
              %ul.dropdown-menu
                %li
                  %a(href="#")
                    = icon('user')
                    %span= t('section.profile')
                %li
                  = link_to destroy_user_session_path, method: :delete do
                    = icon('power-off', t('devise.logout'))
          - else
            %li
              = link_to user_omniauth_authorize_path(:facebook),
                        data: { placement: 'bottom' },
                        title: t('devise.login.facebook') do
                = icon('facebook-square', '', class: 'facebook')
            %li
              = link_to user_omniauth_authorize_path(:google_oauth2),
                        data: { placement: 'bottom' },
                        title: t('devise.login.google') do
                = icon('google-plus-square', '', class: 'google')

app/views/layouts/application.html.haml
!!! 5
%html
  = render 'layouts/head'
  %body(data-dispatch=body_data_dispatch)
    = render 'layouts/navbar'

    #main.container-fluid
      .row
        .col-xs-2.col-sm-5
          = render 'layouts/left_section'

        #content.col-xs-12.col-sm-7.full-content
          = yield
          #zoning-map

    = render 'layouts/flash'
    :javascript
      console.log('INIT: setting current locale');
      I18n.locale = "#{I18n.locale}";